
CREATE TABLE accounts (
  id BIGINT NOT NULL AUTO_INCREMENT,
  email VARCHAR(400) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  role VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
);
